### ISSUE TITLE
GTK from the source code?

### ISSUE THREAD

**Issue by sabriunal** [vixalien/muzika#17]
Hi, do you have a reason to build GTK from the source code?

```
        {
          "name": "gtk",
          "buildsystem": "meson",
          "config-opts": [
            "-Ddemos=false",
            "-Dbuild-testsuite=false",
            "-Dbuild-examples=false",
            "-Dbuild-tests=false"
          ],
          "cleanup": [
            "/bin/*"
          ],
          "sources": [
            {
              "type": "git",
              "url": "https://gitlab.gnome.org/GNOME/gtk.git",
              "commit": "2d2df42a94ec96f1d8c17c261ef8fcf1d9eafe7c"
            }
          ]
        }
```

**Comment by vixalien** [comment]
yes. this is because we use the unreleased version of libadwaita `1.4.alpha` so we can get nice stuff like `AdwNavigationView` etc.

since 1.4 will be released with GNOME 45 in September, I didn't wanna wait that long but instead start working on this right away.

that version of libadwaita requires a version of gtk that's later than the latest one (4.11 I think) because it introduced new features that libadwaita uses internally.

hope this answers your question

**Comment by sabriunal** [comment]
Thanks.
