### ISSUE TITLE
Resuming song after very long time doesn't work

### ISSUE THREAD

**Issue by ondrejkolin** [vixalien/muzika#60]
I sometimes leave the app opened for a very long time. Returning to the app and resuming playback plays the current title until the end to what is already cached. 

Skipping the song plays the next one (or the previous) as expected, maybe some access token is expired and doesn't get refreshed? 

Still enjoying the app ♥️

**Comment by vixalien** [comment]
oh yea. this is because the playback URIs that the API provides have an explicit expire time. that means if you try to access that URI after it has expired, it won't work. I'll work on this as soon as I figure out how to catch the errors that "the stream URI has expired"

another similar problem is that the URIs are scoped to the IP address. i.e if you change your WiFi or even turn off/on a VPN, the URI will stop working and you'll get playback issues. I'll try my best to try work on this issue.
