### ISSUE TITLE
cant run app, recently updated to the newest artifact

### ISSUE THREAD

**Issue by Hedronmx** [vixalien/muzika#61]
Hello! I updated the app and I cant run it. This is the error

```
Gjs-WARNING **: 15:42:11.023: JS ERROR: Error: Invalid parameter interfaces (element 0 was not a GType)
registerGObjectType@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:542:50
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:515:33
registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:74:23
SectionedPlayableList<@resource:///com/vixalien/muzika/js/main.js:14431:14
@resource:///com/vixalien/muzika/js/main.js:14457:7
@file:///app/bin/com.vixalien.muzika:28:6
````

I am running the artifact Update Potfiles - commit [714842a]

**Comment by vixalien** [comment]
will fix this tmr with an update.

are you using the "Flatpak" or "Nightly Flatpak" build

**Comment by Hedronmx** [comment]
No idea, how would I know?? I just click on the read me artifact link

**Comment by vixalien** [comment]
the latest build should now work, albeit with a few errors in the log (and the sidebar will not have headers).

there's nothing i can do on that end since the GTK bug [has been fixed](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6294) but it seems it's not yet included in the newest releases. The error will go on for itself when GTK gets updated.

**Comment by Hedronmx** [comment]
The app runs but I cant play any songs

**Comment by vixalien** [comment]
sorry. I think you will need to install a [Nightly Build](https://github.com/vixalien/muzika/actions/workflows/build-nighly.yml) while waiting for GNOME 45 to release (which will fix the playback issues)
