### ISSUE TITLE
Switching network connection briefly interrupts the playback

### ISSUE THREAD

**Issue by ondrejkolin** [vixalien/muzika#63]
If I toggle the wifi and disconnect ethernet (I do that, because in my office is port 22 limited on internal network) the Muzika playback gets interrupted for a while and resumes again after ~2 secs. 

- Is there a way to detect the interruption of the network stream beforehand? 
  - Maybe some DBUS network manager interface, which could tell you "Network changed", so the player can retry getting the stream again. (if I understand the issue correctly)
  
  Still enjoying the app! Thanks!

**Comment by vixalien** [comment]
hi ondrej. basically, the player is trying to do exactly that.

when you switch networks, the old stream does not work anymore because the streams are scoped to the IP address (and IP addresses change when you switch networks). The reason there's a short delay is because GStreamer usually tries multiple times to fetch the stream (I think it's 3) and gives some time before retrying. Then when it sees that the old stream is not working (HTTP Response 403 - Forbidden) it will request a new stream from YTM's servers (which takes some time) and then the GStreamer pipeline starts buffering again.

so there's really nothing I can do to minimize the delays (yet)

**Comment by ondrejkolin** [comment]
Ok, thanks! I am closing it then. Thanks
