### ISSUE TITLE
[Bug] Sometimes pressing a track loads it but doesn't play it

### ISSUE THREAD

**Issue by vixalien** [vixalien/muzika#93]
When playback is paused and you click on a track, it will just load it but not play it. Same when you click a lyric line.

**Comment by gregthwuen** [comment]
I don't know if it's directly related, but I actually experience the same issue when playback is not paused, including when the autoplay function jumps to the next song in the queue.

Playback only continues when pausing and resuming manually, otherwise it simply displays the loading bar indefinitely:

![image](https://github.com/vixalien/muzika/assets/41543402/f9a37d7d-f66e-43dc-afb7-f3de84e893b0)

**Comment by vixalien** [comment]
Yes. I have a local branch that actually fixes this and other shenanigans with the player.

I'll create a PR soon and tag you.
